import type { Metadata } from "next";
import "./global.css";
import { Poppins } from "next/font/google";
import { Open_Sans } from "next/font/google";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ['300','400', '500', '600', '700']
});
export const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ['300','400', '500', '600', '700']
});

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Template from "./template";
config.autoAddCss = false

export const metadata = {
  title: 'Sacha - Portfolio Website',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Template>
          {children}
        </Template>
      </body>
    </html>
  )
}
