import type { Metadata } from "next";
import "./global.css";
import { Poppins } from "next/font/google";
import Navbar from "./_components/navbar/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ['200','300','400', '500', '600', '700', '800', '900']
});

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

export const metadata = {
  title: 'Sacha - Portfolio Website',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
        <div id="navbar" className="fixed top-0 right-[3%]">
          <Navbar />
        </div>
      </body>
    </html>
  )
}
